{% set name = "orange-widget-base" %}
{% set version = "4.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 193055dbee8701ad62d5471c5287b092ce53bb77f7f810ec68bf96816f6acaa2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.1.27,<0.2a
    - typing_extensions >=3.7.4.3
    # appnope is skipped here since if we add it package is not noarch: python anymore
    # and appnope is used just optionally in tests

test:
  imports:
    - orangewidget.widget
    - orangewidget.gui

about:
  home: https://github.com/biolab/orange-widget-base
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Base Widget for Orange Canvas

  description: |
    This project implements the base OWBaseWidget class and utilities for use
    in Orange Canvas workflows.

  doc_url: https://orange-widget-base.readthedocs.io/
  dev_url: https://github.com/biolab/orange-widget-base/

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
