travis:
  secure:
    BINSTAR_TOKEN: ioRVfJMzEaSZuC300yJiUZzjlhbQiscfJF93quqzF2+YmdF/hQj5LvE/FV/TqClnzU7tWy1sjXC7v96B2YOMmez5E/YHvc0awf2iU5xE8TSyJ4iHYrwnRS/cJJCZr/AlZUVaMecUxgCOEnVzxrTpy96o6BOGkXbtVtx3EJQd1+8x/kBNbBVE7UVJqIYnjTCq1ymcOx4UlTZB0BH7uRsHZHdo/bb11nF6+JZ2Y2RrwZSR3AmsW9XZDSYj1pmdomKEqW52CIQryjMj+1pkmnigI5czZ4UYAl4R4e0ozTkRrp5yuTCZLCfs1pVDJGzARshio5DdX8hrDINRiUPWB+0RePO2ZrYhztUCrrVEZpqkNV3UDWGMJJVhCMnzalCjIr3GDh4i9Iu3RfVF3TFOYWWJbscL/ArQRQdg2NUmimOLg2zDRmPCWRbYj9sH3jRVxWSTe+AAVj/gWthNj62s+kDBYiBebbfvyvBOK7CRK6cAS5J6hZnRcmEOyTiIbH/m6BQkIrpJfeDEws5tm4ytXWN9iR5i8J6ReSBAwcnlA2SbHA4U0mTJECEVzkdOnZ7/HFIekWPViF0G1n7TY0NqLrLqQBJxLVeoFZqa8esuFk5thNPypC7Nj8rwjzeJrhG0wAJ9ZZkhiTBlQgYqtlGMG+gihS0OClZhz/Wvl98r5sFahNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
